version: "3.4"

services:
  rails_app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: rails_app
    container_name: rails_app
    ports:
      - "3000:3000"
    networks:
      - app_network
    env_file: rails_app.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: webserver
    container_name: webserver
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      rails_app:
        condition: service_healthy

  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
