name: Docker Build and Push to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 573770898769.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build and push Rails image to ECR
      run: |
        docker build -t my-rails-app -f docker/app/Dockerfile .
        docker tag my-rails-app:latest 573770898769.dkr.ecr.ap-south-1.amazonaws.com/rails_app:latest
        docker push 573770898769.dkr.ecr.ap-south-1.amazonaws.com/rails_app:latest

    - name: Build and push Webserver image to ECR
      run: |
        docker buildx build --load -t my-webserver -f ./docker/nginx/Dockerfile .
        docker tag my-webserver:latest 573770898769.dkr.ecr.ap-south-1.amazonaws.com/webserver:latest
        docker push 573770898769.dkr.ecr.ap-south-1.amazonaws.com/webserver:latest

